server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dryworld-qk/cloud_text.git
          search-paths: config
          username: cloud_test
          password: 2292174382@qq.com
          skip-ssl-validation: true
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
