server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dryworld-qk/cloud_text.git
          search-paths: config
          clone-on-start: true
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
